### PR TITLE
Export public API properly

### PR DESCRIPTION
**Pull request by yanovs**
* Export public API properly
  * Originally, I implemented this using `__all__`, but upon more reading, it looks like the "redundant import" is the more canonical way to export the public API.
  * https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface
  * https://github.com/microsoft/pylance-release/issues/856#issuecomment-763793949
  * https://github.com/microsoft/pylance-release/issues/2574#issuecomment-1100806042
* Update `README` examples

### CODE REVIEW

**Comment by adshieh** [comment]
One nice aspect of `__all__` is that flake8 recognizes it, but keeping `__all__` updated is a pain.

**Comment by yanovs** [comment]
> One nice aspect of `__all__` is that flake8 recognizes it, but keeping `__all__` updated is a pain.

My thoughts exactly! I considered keeping it in for that reason, but then decided not to because of the maintenance cost.

**Comment by adshieh** [comment]
> > One nice aspect of `__all__` is that flake8 recognizes it, but keeping `__all__` updated is a pain.
> 
> My thoughts exactly! I considered keeping it in for that reason, but then decided not to because of the maintenance cost.

If we switch from flake8 to ruff, which we've been doing internally, ruff respects the redundant import.

**Comment by yanovs** [comment]
> > > One nice aspect of `__all__` is that flake8 recognizes it, but keeping `__all__` updated is a pain.
> > 
> > 
> > My thoughts exactly! I considered keeping it in for that reason, but then decided not to because of the maintenance cost.
> 
> If we switch from flake8 to ruff, which we've been doing internally, ruff respects the redundant import.

Yeah, absolutely, I agree we should switch. `ruff` is great--can't wait for more tools to be Rust-based. I'll do that in the next month or so then.

On a related note, I'll look into updating the `mypy` settings per https://careers.wolt.com/en/blog/tech/professional-grade-mypy-configuration and https://justincaustin.com/blog/mypy-tips-and-tricks/, assuming it's not overly onerous. And finally, maybe look into [`nox`](https://nox.thea.codes/en/stable/) over `tox` too.

**Comment by yanovs** [comment]
Just for sake of completeness, note that `mypy` uses the exact same conventions as `pyright`: https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport

**Pull request merged**
